#spring
spring.application.name=TgBdayBot
spring.liquibase.change-log=classpath:db/changelog/master-changelog.yaml
spring.liquibase.enabled=true
spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.pool-name=HikariPool-1
spring.datasource.hikari.auto-commit=true
#telegram
telegram.botName=${TELEGRAM_BOT_NAME}
telegram.token=${TELEGRAM_BOT_TOKEN}